### ISSUE TITLE
Support for v2 CDK imports from aws-cdk-lib

### ISSUE THREAD

**Issue by eneskaya** [skyhookadventure/cdk-lambda-nodejs-mock#2]
We've been using this package very successfully for the last couple of months and I believe this is a great idea! I am now at the process of migrating over to CDK v2, replacing all the single imports with `aws-cdk-lib`. That seems to break the usage of this package. Maybe someone can help, here is the situation.

## Observed Behaviour

The `NodeJsFunction` construct does not seem to be replaced during test runs (`Bundling asset...`)

```

 PASS  tests/stacks/image-publishing/image-publishing-stack.spec.ts (39.897 s)

  ...f760b1c1390dd30f2b10b8851b7024228fd904f6e1420f9eba4cc4b/index.js  781.1kb
  ...b1c1390dd30f2b10b8851b7024228fd904f6e1420f9eba4cc4b/index.js.map    2.6mb

Bundling asset Assets-unittest/AssetsImportTriggerLambda/Code/Stage...
$ /infrastructure/node_modules/.bin/esbuild --bundle /.../src/assets-import-trigger/index.ts --target=node14 --platform=node --outfile=/private/var/folders/s2/psmmz0rj0hb2vsm37ls38nmx4_v6kl/T/cdk.outb3cs2t/bundling-temp-60214bf8a118e918d1c93c12cb51f5eeafa8d8fb0140f162a12c0aebd0be371b/index.js --minify --sourcemap --external:aws-lambda --external:aws-sdk
```

### Setup change
Before, our Lambda constructs with `NodeJsFunction` looked like this

```ts
import { NodejsFunction } from '@aws-cdk/aws-lambda-nodejs'

...

const lambda = new NodeJsFunction(this, 'Lambda', {...})
```

After switching to `aws-cdk-lib` you get

```ts
import { aws_lambda_nodejs as lambda_nodejs } from 'aws-cdk-lib'

...

const lambda = new lambda_nodejs.NodejsFunction(this, 'Lambda', {...})
```

Our `jest.config.js` with the `moduleNameMapper` changed from

```js
module.exports = {
  ...,
  moduleNameMapper: {
    '@aws-cdk/aws-lambda-nodejs': 'cdk-lambda-nodejs-mock'
  }
}
```

to

```js
module.exports = {
  ...,
  moduleNameMapper: {
    'aws-cdk-lib/aws_lambda_nodejs': 'cdk-lambda-nodejs-mock'
  }
}
```

### Environment & Dependencies
```
cdk-lambda-nodejs-mock@2.0.2
aws-cdk-lib@2.34.0
jest@28.1.3
node@14.17.6
typescript@4.7.4
```

I guess it's just the way we map the module in the `jest.config.js`, but I couldn't find the mistake really. Appreciate some help, thanks 🙏

**Comment by alan-cooney** [comment]
Just seen this - apologies for that! In general I think that mocking mostly isn't needed with the latest CDK as compilers are much faster nowdays (and it's nice to check that the function can be compiled).

**Comment by eneskaya** [comment]
> Just seen this - apologies for that! In general I think that mocking mostly isn't needed with the latest CDK as compilers are much faster nowdays (and it's nice to check that the function can be compiled). 

I agree, you can close this issue. Thanks!
